### ISSUE TITLE
Stage Display API accessibility 

### ISSUE THREAD

**Issue by davidlentsch** [kikeh/PP6RemoteAPI#1]
Hello there, can you explain how to use the functions within the StageDisplay class? I can't seem to get the `send_message` function to work. Below is my terminal output.

Thoughts?

david@david-virtual-machine:~$ python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from PP6RemoteAPI import PP6RemoteAPIClient as PP6
>>> client == PP6(host='172.16.198.1', port=49911, password='password')
>>> client.authenticate()
{'controller': 1, 'authenticated': 1, 'error': '', 'action': 'authenticate'}
>>> client.StageDisplay
Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
AttributeError: 'PP6RemoteAPIClient' object has no attribute 'StageDisplay'
>>> client.send_message("Test")
Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
AttributeError: 'PP6RemoteAPIClient' object has no attribute 'send_message'
>>>

**Comment by kikeh** [comment]
Hi @davidlentsch ! The StageDisplay class is only an instantiation of the object returned by PP6.
So, for using stage display messages, you can either:
- Use `stage_displays`, which will return the array of available Stage Display sets.
- Use `current_stage_display`, which will return the currently selected Stage Display set.
Either way, you will end up having a StageDisplay object, being able now to use the function `send_message`.

Here are some examples:
```python
from PP6RemoteAPI import PP6RemoteAPIClient as PP6
client = PP6(...)
client.current_stage_display
# prints <StageDisplay: Lyrics | current>
# Send message to current Stage Display set
client.current_stage_display.send_message('Hello there!')

# Select another Stage Display set from the available ones
stage_displays = client.stage_displays
stage_displays
# prints [<StageDisplay: Lyrics | current>, <StageDisplay: Messages>]
client.stage_display_set_display(1)
client.current_stage_display
# prints <StageDisplay: Messages | current>
# And now, send message again
client.current_stage_display.send_message('Hello there!')
```

Let me know if you were able to solve your issue or if you have any more questions :)

**Comment by kikeh** [comment]
One more thing, I recently updated the package to make it compatible with Python 3.6 (it was only 3.7 compatible because of an `asyncio` function), so make sure you are using the latest version.

**Comment by kikeh** [comment]
Ok, I think this has been answered, so I will close this issue.
If you need any more information, let me know :)
